<?php
$repArr = array(
	'α'=>'Ó',
	'π'=>'Ò',
	'╓'=>'Í',
	'╡'=>'Á',
	'Θ'=>'Ú',
	'∙'=>'^',
	'∩'=>'\'',
	'╘'=>'È',
	'╥'=>'Ê',
	'╢'=>'Â',
	'├│'=>'ó',
	'┼'=>'+',
	'│'=>'|',

	'!v065!<FUNCIONES ARMONICAS>'=>'!v065!FUNCIONES ARMONICAS',
	'!v007!PUBLICACIONES' => '!v007!PUBLICACION',
	/*reemplazar el amperzand al final*/
	'&'=>'&amp;',
	'<Reisz>' =>'Reisz',
	'<Wilder>'=>'Wilder',
	'<Fellini>'=>'Fellini',
	'<Rhea>'=>'Rhea',
	'<Causse>'=>'Causse',
	'<Szoygi>'=>'Szoygi',
	'<Le Corbusier>'=>'Le Corbusier',
	'<Aalto, Alvar>'=>'Aalto, Alvar',
	'<Wright, Frank Lloyd>'=>'Wright, Frank Lloyd',
	'<Ravera>'=>'Ravera',
	'<Pizzello>'=>'Pizzello',
	'<Weber>'=>'Weber',
	'<Zimmermann>'=>'Zimmermann',
	'<Churba>'=>'Churba',
	'<Allombert>'=>'Allombert',
	'<Arnault>'=>'Arnault',
	'<Chevassu>'=>'Chevassu',
	'<Eberhard>'=>'Eberhard',
	'<Fuskiewicz>'=>'Fuskiewicz',
	'<Gawrak>'=>'Gawrak',
	'<Gauthier>'=>'Gauthier',
	'<Haudiquet>'=>'Haudiquet',
	'<Estrada>'=>'Estrada',
	'<'=>'',
	'>'=>'',
	'^@'=>'',
	'{a'=>'á',
	'{e'=>'é',
	'{i'=>'í',
	'{o'=>'ó',
	'{u'=>'ú',
	'ANALES...'=>'ANALES DEL INSTITUTO DE ARTE AMERICANO E INVESTIGACIONES ESTÉTICAS',
	'Anales...'=>'ANALES DEL INSTITUTO DE ARTE AMERICANO E INVESTIGACIONES ESTÉTICAS',
	'ANUARIO...'=>'ANUARIO - ACADEMIA NACIONAL DE BELLAS ARTES - [ANU ANBA]',
	'ARCH. DESIGN'=>'ARCHITECTURAL DESIGN',
	'ARCH. DIGEST'=>'ARCHITECTURAL DIGEST',
	'ARCH. MONOGRAPHS'=>'[NO MIGRAR, PASAN A LIBROS]',
	'ARCH. RECORD'=>'ARCHITECTURAL RECORD',
	'Arch. Record'=>'ARCHITECTURAL RECORD',
	'ARCH. REVIEW'=>'ARCHITECTURAL REVIEW',
	'Arch. Review'=>'ARCHITECTURAL REVIEW',
	'Arch. review'=>'ARCHITECTURAL REVIEW',
	'ARQUITECTURA Y COMUNIDAD NACIO'=>'ARQUITECTURA Y COMUNIDAD NACIONAL',


);

